# Generated by Django 5.0.7 on 2026-01-19 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_index', models.PositiveSmallIntegerField(default=1)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('finalized', 'Finalized')], default='open', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('consolidation_days', models.PositiveIntegerField(default=14)),
                ('horizon_days', models.PositiveIntegerField(default=60)),
                ('schedule_weights', models.JSONField(blank=True, default=dict)),
                ('swap_requires_approval', models.BooleanField(default=True)),
                ('notify_on_cancellation', models.BooleanField(default=True)),
                ('auto_assign_on_decline', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcolyteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.community')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acolytes', to='core.parish')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_state', models.CharField(choices=[('proposed', 'Proposed'), ('published', 'Published'), ('locked', 'Locked')], default='proposed', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.acolyteprofile')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.assignmentslot')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ruleset_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventseries_created', to=settings.AUTH_USER_MODEL)),
                ('default_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.community')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventseries_updated', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('liturgy_label', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_created', to=settings.AUTH_USER_MODEL)),
                ('event_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventseries')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentslot',
            name='mass_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.massinstance'),
        ),
        migrations.CreateModel(
            name='MassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('time', models.TimeField()),
                ('rrule_text', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.community')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='massinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.masstemplate'),
        ),
        migrations.CreateModel(
            name='MassOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_type', models.CharField(choices=[('cancel_instance', 'Cancel instance'), ('move_instance', 'Move instance'), ('change_requirements', 'Change requirements'), ('change_display_fields', 'Change display fields')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.massinstance')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='massinstance',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish'),
        ),
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'unique_together': {('parish', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('canceled_by_acolyte', 'Canceled'), ('replaced', 'Replaced'), ('no_show', 'No show')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='core.assignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='community',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish'),
        ),
        migrations.AddField(
            model_name='assignmentslot',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish'),
        ),
        migrations.CreateModel(
            name='AcolyteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services_last_30_days', models.PositiveIntegerField(default=0)),
                ('services_last_90_days', models.PositiveIntegerField(default=0)),
                ('confirmation_rate', models.FloatField(default=0.0)),
                ('cancellations_rate', models.FloatField(default=0.0)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('credit_balance', models.IntegerField(default=0)),
                ('acolyte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcolyteIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_frequency_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('willingness_level', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('acolyte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcolyteCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('reason_code', models.CharField(choices=[('served_unpopular_slot', 'Served unpopular slot'), ('accepted_last_minute_substitution', 'Accepted last minute substitution'), ('high_attendance_streak', 'High attendance streak'), ('received_high_demand_assignment', 'Received high demand assignment')], max_length=40)),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assignment')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcolyteAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('unavailable', 'Unavailable'), ('available_only', 'Available only')], max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.community')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParishMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('roles', models.ManyToManyField(blank=True, to='core.membershiprole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentslot',
            name='position_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positiontype'),
        ),
        migrations.CreateModel(
            name='AcolyteQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualified', models.BooleanField(default=True)),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positiontype')),
            ],
        ),
        migrations.CreateModel(
            name='AcolytePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preference_type', models.CharField(choices=[('preferred_community', 'Preferred community'), ('avoid_community', 'Avoid community'), ('preferred_timeslot', 'Preferred timeslot'), ('preferred_mass_template', 'Preferred mass template'), ('preferred_position', 'Preferred position'), ('avoid_position', 'Avoid position'), ('preferred_function', 'Preferred function'), ('avoid_function', 'Avoid function'), ('preferred_partner', 'Preferred partner'), ('avoid_partner', 'Avoid partner')], max_length=40)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=50)),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('target_acolyte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='core.acolyteprofile')),
                ('target_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.community')),
                ('target_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.functiontype')),
                ('target_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.masstemplate')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.positiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositionTypeFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.functiontype')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positiontype')),
            ],
        ),
        migrations.AddField(
            model_name='positiontype',
            name='functions',
            field=models.ManyToManyField(blank=True, through='core.PositionTypeFunction', to='core.functiontype'),
        ),
        migrations.CreateModel(
            name='RequirementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='masstemplate',
            name='default_requirement_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requirementprofile'),
        ),
        migrations.AddField(
            model_name='massinstance',
            name='requirement_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requirementprofile'),
        ),
        migrations.CreateModel(
            name='RequirementProfilePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positiontype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.requirementprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swap_type', models.CharField(choices=[('acolyte_swap', 'Acolyte swap'), ('role_swap', 'Role swap')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('from_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_from', to='core.assignmentslot')),
                ('mass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.massinstance')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('requestor_acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='core.acolyteprofile')),
                ('target_acolyte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_targets', to='core.acolyteprofile')),
                ('to_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_to', to='core.assignmentslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('parish', 'code')},
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=50)),
                ('diff_json', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parish')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_audite_entity__e1955d_idx'), models.Index(fields=['parish', 'timestamp'], name='core_audite_parish__8cf4e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acolyteprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('parish', 'user'), name='unique_acolyte_user_per_parish'),
        ),
        migrations.AlterUniqueTogether(
            name='parishmembership',
            unique_together={('parish', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='assignmentslot',
            unique_together={('mass_instance', 'position_type', 'slot_index')},
        ),
        migrations.AlterUniqueTogether(
            name='acolytequalification',
            unique_together={('parish', 'acolyte', 'position_type')},
        ),
        migrations.AlterUniqueTogether(
            name='positiontypefunction',
            unique_together={('position_type', 'function_type')},
        ),
        migrations.AlterUniqueTogether(
            name='positiontype',
            unique_together={('parish', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='massinstance',
            unique_together={('parish', 'starts_at', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='requirementprofileposition',
            unique_together={('profile', 'position_type')},
        ),
    ]
