# Generated by Django 5.0.7 on 2026-01-20 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='candidate_pool',
            field=models.CharField(choices=[('all', 'All'), ('interested_only', 'Interested only')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='parish',
            name='default_mass_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='parish',
            name='min_rest_minutes_between_masses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('conflict_action', models.CharField(choices=[('keep', 'Keep existing'), ('cancel_existing', 'Cancel existing'), ('move_existing', 'Move existing'), ('skip', 'Skip')], default='keep', max_length=20)),
                ('move_to_date', models.DateField(blank=True, null=True)),
                ('move_to_time', models.TimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.community')),
                ('event_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.eventseries')),
                ('move_to_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_occurrences', to='core.community')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('requirement_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requirementprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
                ('proposed_acolyte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acolyteprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignmentslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acolyteprofile')),
                ('event_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventseries')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish')),
            ],
            options={
                'unique_together': {('event_series', 'acolyte')},
            },
        ),
    ]
