# Generated by Django 5.0.7 on 2026-01-20 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventseries_candidate_pool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='massinstance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='massinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('parish', 'starts_at', 'community'), name='unique_scheduled_mass_per_slot'),
        ),
    ]
