# Generated by Django 5.0.7 on 2026-01-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_massinstance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('declined', 'Declined'), ('canceled', 'Canceled'), ('replaced', 'Replaced'), ('replaced_by_solver', 'Replaced by solver'), ('manual_unassign', 'Manual unassign'), ('swap', 'Swap')], max_length=30),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='open_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.assignmentslot'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('slot',), name='unique_active_assignment_per_slot'),
        ),
    ]
