# Generated by Django 5.0.7 on 2026-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_end_reason_assignment_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='resolved_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='resolved_reason',
            field=models.CharField(blank=True, choices=[('mass_canceled', 'Mass canceled'), ('slot_not_required', 'Slot not required'), ('covered_externally', 'Covered externally'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('canceled', 'Canceled'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
