# Generated by Django 5.0.7 on 2026-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_replacementrequest_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentslot',
            name='external_coverage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentslot',
            name='externally_covered',
            field=models.BooleanField(default=False),
        ),
    ]
