# Generated by Django 5.0.7 on 2026-01-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventseries_is_active'),
    ]

    operations = [
        # Adiciona suporte ao end_reason "moved_to_another_slot" usado na função move_acolyte_to_slot
        # Esta migração apenas documenta a adição do choice ao modelo Assignment.END_REASON_CHOICES
        # Não há mudanças no schema do banco de dados
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            elidable=True,
        ),
    ]
