# Generated by Django 5.0.7 on 2026-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_moved_to_another_slot_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolyteprofile',
            name='scheduling_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('reserve', 'Reserva tecnica')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='acolyteavailabilityrule',
            name='rule_type',
            field=models.CharField(choices=[('unavailable', 'Indisponivel'), ('available_only', 'Disponivel apenas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='acolytecreditledger',
            name='reason_code',
            field=models.CharField(choices=[('served_unpopular_slot', 'Serviu em horario pouco procurado'), ('accepted_last_minute_substitution', 'Aceitou substituicao de ultima hora'), ('high_attendance_streak', 'Boa sequencia de presencas'), ('received_high_demand_assignment', 'Recebeu funcao disputada')], max_length=40),
        ),
        migrations.AlterField(
            model_name='acolyteintent',
            name='willingness_level',
            field=models.CharField(choices=[('low', 'Baixo'), ('normal', 'Normal'), ('high', 'Alto')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='acolytepreference',
            name='preference_type',
            field=models.CharField(choices=[('preferred_community', 'Preferir comunidade'), ('avoid_community', 'Evitar comunidade'), ('preferred_timeslot', 'Preferir horario'), ('preferred_mass_template', 'Preferir modelo'), ('preferred_position', 'Preferir funcao'), ('avoid_position', 'Evitar funcao'), ('preferred_function', 'Preferir funcao base'), ('avoid_function', 'Evitar funcao base'), ('preferred_partner', 'Preferir parceiro'), ('avoid_partner', 'Evitar parceiro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='acolyteprofile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediario'), ('senior', 'Senior')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_state',
            field=models.CharField(choices=[('proposed', 'Proposta'), ('published', 'Publicada'), ('locked', 'Consolidada')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('declined', 'Recusado'), ('canceled', 'Cancelado'), ('replaced', 'Substituido'), ('replaced_by_solver', 'Substituido pelo sistema'), ('manual_unassign', 'Removido manualmente'), ('moved_to_another_slot', 'Movido para outra posicao'), ('swap', 'Trocado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assignmentslot',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('assigned', 'Atribuida'), ('finalized', 'Finalizada')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('declined', 'Recusada'), ('canceled_by_acolyte', 'Cancelada'), ('replaced', 'Substituida'), ('no_show', 'Nao compareceu')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='conflict_action',
            field=models.CharField(choices=[('keep', 'Manter existente'), ('cancel_existing', 'Cancelar existente'), ('move_existing', 'Mover existente'), ('skip', 'Ignorar')], default='keep', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='candidate_pool',
            field=models.CharField(choices=[('all', 'Todos'), ('interested_only', 'Somente interessados')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='massinstance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('canceled', 'Cancelada')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='massoverride',
            name='override_type',
            field=models.CharField(choices=[('cancel_instance', 'Cancelar missa'), ('move_instance', 'Mover missa'), ('change_requirements', 'Alterar requisitos'), ('change_display_fields', 'Alterar exibicao')], max_length=40),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='resolved_reason',
            field=models.CharField(blank=True, choices=[('mass_canceled', 'Missa cancelada'), ('slot_not_required', 'Funcao nao necessaria'), ('covered_externally', 'Coberto externamente'), ('other', 'Outro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('assigned', 'Atribuida'), ('canceled', 'Cancelada'), ('resolved', 'Resolvida')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('awaiting_approval', 'Aguardando aprovacao'), ('accepted', 'Aceita'), ('rejected', 'Recusada'), ('canceled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='swap_type',
            field=models.CharField(choices=[('acolyte_swap', 'Troca de acolito'), ('role_swap', 'Troca de funcao')], max_length=20),
        ),
    ]
