# Generated by Django 5.0.7 on 2026-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_manual_adjustment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
