# Generated by Django 5.0.7 on 2026-01-24 00:00

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def forward_fill_mass_interests(apps, schema_editor):
    EventInterest = apps.get_model("core", "EventInterest")
    MassInstance = apps.get_model("core", "MassInstance")
    MassInterest = apps.get_model("core", "MassInterest")

    interested_entries = EventInterest.objects.filter(interested=True)
    if not interested_entries.exists():
        return

    series_ids = list(interested_entries.values_list("event_series_id", flat=True).distinct())
    masses_by_series = defaultdict(list)
    for mass_id, series_id, parish_id in MassInstance.objects.filter(event_series_id__in=series_ids).values_list(
        "id", "event_series_id", "parish_id"
    ):
        masses_by_series[series_id].append((mass_id, parish_id))

    bulk = []
    for interest in interested_entries.iterator():
        for mass_id, parish_id in masses_by_series.get(interest.event_series_id, []):
            bulk.append(
                MassInterest(
                    parish_id=parish_id,
                    mass_instance_id=mass_id,
                    acolyte_id=interest.acolyte_id,
                    interested=True,
                )
            )
    if bulk:
        MassInterest.objects.bulk_create(bulk, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_swap_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MassInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("interested", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("acolyte", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.acolyteprofile")),
                ("mass_instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.massinstance")),
                ("parish", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.parish")),
            ],
            options={
                "unique_together": {("mass_instance", "acolyte")},
            },
        ),
        migrations.RunPython(forward_fill_mass_interests, migrations.RunPython.noop),
    ]
