# Generated by OpenCode on 2026-01-24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_mass_interest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parish",
            name="claim_auto_approve_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parish",
            name="claim_auto_approve_hours",
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name="parish",
            name="claim_require_coordination",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PositionClaimRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_target", "Aguardando titular"),
                            ("pending_coordination", "Aguardando coordenacao"),
                            ("scheduled_auto_approve", "Aguardando prazo"),
                            ("approved", "Aprovada"),
                            ("rejected", "Recusada"),
                            ("expired", "Expirada"),
                        ],
                        default="pending_target",
                        max_length=30,
                    ),
                ),
                (
                    "approval_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("target", "Titular"),
                            ("coordination", "Coordenacao"),
                            ("auto", "Automatica"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "resolution_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("holder_approved", "Titular aprovou"),
                            ("holder_confirmed", "Titular confirmou"),
                            ("holder_rejected", "Titular recusou"),
                            ("holder_selected_other", "Outro solicitante escolhido"),
                            ("coordination_approved", "Aprovada pela coordenacao"),
                            ("coordination_rejected", "Recusada pela coordenacao"),
                            ("auto_approved", "Aprovada pelo prazo"),
                            ("auto_expired", "Expirada pelo prazo"),
                            ("requestor_canceled", "Cancelada pelo solicitante"),
                            ("assignment_changed", "Escala alterada"),
                        ],
                        max_length=40,
                    ),
                ),
                ("auto_approve_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "parish",
                    models.ForeignKey(on_delete=models.CASCADE, to="core.parish"),
                ),
                (
                    "requestor_acolyte",
                    models.ForeignKey(on_delete=models.CASCADE, related_name="position_claim_requests", to="core.acolyteprofile"),
                ),
                (
                    "slot",
                    models.ForeignKey(on_delete=models.CASCADE, related_name="position_claims", to="core.assignmentslot"),
                ),
                (
                    "target_assignment",
                    models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="position_claims", to="core.assignment"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="positionclaimrequest",
            index=models.Index(fields=["slot", "status"], name="core_positi_slot_id_6a0f4c_idx"),
        ),
        migrations.AddIndex(
            model_name="positionclaimrequest",
            index=models.Index(fields=["requestor_acolyte", "status"], name="core_positi_reques_0f3c65_idx"),
        ),
    ]
