# Generated by Django 5.0.7 on 2026-01-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_position_claim_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='positionclaimrequest',
            new_name='core_positi_slot_id_5cc0fb_idx',
            old_name='core_positi_slot_id_6a0f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='positionclaimrequest',
            new_name='core_positi_request_e0c581_idx',
            old_name='core_positi_reques_0f3c65_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('declined', 'Recusado'), ('canceled', 'Cancelado'), ('replaced', 'Substituido'), ('replaced_by_solver', 'Substituido pelo sistema'), ('manual_unassign', 'Removido manualmente'), ('moved_to_another_slot', 'Movido para outra posicao'), ('swap', 'Trocado'), ('claim_transfer', 'Transferido por solicitacao')], max_length=30),
        ),
    ]
