# Generated by Django 5.0.7 on 2026-01-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_core_positi_slot_id_6a0f4c_idx_core_positi_slot_id_5cc0fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='interest_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
