# Generated by Django 5.0.7 on 2026-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('skipped', 'Ignorada')], default='pending', max_length=20),
        ),
    ]
