# Generated by Django 5.0.7 on 2026-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulejobrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Concluido'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
