from django.urls import path

from accounts.urls import urlpatterns as account_urls
from web import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("calendar/", views.calendar_month, name="calendar_month"),
    path("calendar/<int:instance_id>/", views.mass_detail, name="mass_detail"),
    path("calendar/<int:instance_id>/update/", views.mass_update, name="mass_update"),
    path("calendar/<int:instance_id>/move/", views.mass_move, name="mass_move"),
    path("calendar/<int:instance_id>/cancel/", views.mass_cancel, name="mass_cancel"),
    path("calendar/<int:instance_id>/slots/<int:slot_id>/assign/", views.slot_assign, name="slot_assign"),
    path("calendar/<int:instance_id>/slots/<int:slot_id>/move/", views.move_acolyte, name="move_acolyte"),
    path("calendar/<int:instance_id>/slots/<int:slot_id>/replace/", views.slot_replace, name="slot_replace"),
    path(
        "calendar/<int:instance_id>/slots/<int:slot_id>/confirm/",
        views.slot_confirm_assignment,
        name="slot_confirm_assignment",
    ),
    path(
        "calendar/<int:instance_id>/slots/<int:slot_id>/claim/",
        views.position_claim_create,
        name="position_claim_create",
    ),
    path(
        "calendar/<int:instance_id>/slots/<int:slot_id>/remove/",
        views.slot_remove_assignment,
        name="slot_remove_assignment",
    ),
    path("templates/", views.template_list, name="template_list"),
    path("templates/new/", views.template_create, name="template_create"),
    path("templates/generate/", views.generate_instances, name="generate_instances"),
    path("structure/communities/", views.structure_communities_list, name="structure_communities_list"),
    path("structure/communities/new/", views.structure_community_create, name="structure_community_create"),
    path("structure/communities/<int:community_id>/edit/", views.structure_community_edit, name="structure_community_edit"),
    path("structure/communities/<int:community_id>/toggle/", views.structure_community_toggle, name="structure_community_toggle"),
    path("structure/roles/", views.structure_roles_list, name="structure_roles_list"),
    path("structure/roles/new/", views.structure_role_create, name="structure_role_create"),
    path("structure/roles/<int:role_id>/edit/", views.structure_role_edit, name="structure_role_edit"),
    path("structure/roles/<int:role_id>/toggle/", views.structure_role_toggle, name="structure_role_toggle"),
    path("structure/roles/<int:role_id>/delete/", views.structure_role_delete, name="structure_role_delete"),
    path(
        "structure/requirement-profiles/",
        views.structure_requirement_profiles_list,
        name="structure_requirement_profiles_list",
    ),
    path(
        "structure/requirement-profiles/new/",
        views.structure_requirement_profile_create,
        name="requirement_profile_create",
    ),
    path(
        "structure/requirement-profiles/<int:profile_id>/edit/",
        views.structure_requirement_profile_edit,
        name="structure_requirement_profile_edit",
    ),
    path(
        "structure/requirement-profiles/<int:profile_id>/toggle/",
        views.structure_requirement_profile_toggle,
        name="structure_requirement_profile_toggle",
    ),
    path("roster/", views.roster_view, name="roster_view"),
    path("roster/export/pdf/", views.roster_export_pdf, name="roster_export_pdf"),
    path("roster/export/whatsapp/", views.roster_export_whatsapp, name="roster_export_whatsapp"),
    path("roster/open-slots/", views.roster_open_slots, name="roster_open_slots"),
    path("roster/open-slots/<int:slot_id>/assign/", views.roster_open_slot_assign, name="roster_open_slot_assign"),
    path("roster/open-slots/<int:slot_id>/mark-external/", views.roster_open_slot_mark_external, name="roster_open_slot_mark_external"),
    path("roster/open-slots/<int:slot_id>/candidates/", views.roster_open_slot_get_candidates, name="roster_open_slot_get_candidates"),
    path("events/", views.event_series_list, name="event_series_list"),
    path("events/new/", views.event_series_create, name="event_series_create"),
    path("events/new/days/", views.event_series_days, name="event_series_days"),
    path("events/<int:series_id>/", views.event_series_detail, name="event_series_detail"),
    path("events/<int:series_id>/edit/", views.event_series_edit, name="event_series_edit"),
    path("events/<int:series_id>/occurrences/", views.event_series_occurrences, name="event_series_occurrences"),
    path("events/<int:series_id>/archive/", views.event_series_archive, name="event_series_archive"),
    path("events/<int:series_id>/unarchive/", views.event_series_unarchive, name="event_series_unarchive"),
    path("events/<int:series_id>/delete/", views.event_series_delete, name="event_series_delete"),
    path("scheduling/", views.scheduling_dashboard, name="scheduling_dashboard"),
    path("scheduling/publish/preview/", views.scheduling_publish_preview, name="scheduling_publish_preview"),
    path("scheduling/publish/apply/", views.scheduling_publish_apply, name="scheduling_publish_apply"),
    path("scheduling/jobs/<int:job_id>/", views.schedule_job_detail, name="schedule_job_detail"),
    path("audit/", views.audit_log, name="audit_log"),
    path("reports/frequency/", views.reports_frequency, name="reports_frequency"),
    path("replacements/", views.replacement_center, name="replacement_center"),
    path("replacements/<int:request_id>/assign/", views.replacement_assign, name="replacement_assign"),
    path("replacements/<int:request_id>/pick/", views.replacement_pick, name="replacement_pick"),
    path("replacements/<int:request_id>/resolve/", views.replacement_resolve, name="replacement_resolve"),
    path("acolytes/", views.acolyte_list, name="acolyte_list"),
    path("acolytes/link/", views.acolyte_link, name="acolyte_link"),
    path("people/", views.people_directory, name="people_directory"),
    path("people/new/", views.people_create, name="people_create"),
    path("people/user/<int:user_id>/", views.people_user_detail, name="people_user_detail"),
    path("people/acolyte/<int:acolyte_id>/", views.people_acolyte_detail, name="people_acolyte_detail"),
    # Acolyte hub actions
    path("people/acolyte/<int:acolyte_id>/intent/", views.acolyte_update_intent, name="acolyte_update_intent"),
    path("people/acolyte/<int:acolyte_id>/credits/adjust/", views.acolyte_adjust_credits, name="acolyte_adjust_credits"),
    path("people/acolyte/<int:acolyte_id>/notifications/", views.acolyte_update_notifications, name="acolyte_update_notifications"),
    path("people/acolyte/<int:acolyte_id>/notifications/<int:notification_id>/resend/", views.acolyte_resend_notification, name="acolyte_resend_notification"),
    path("people/acolyte/<int:acolyte_id>/assign/", views.acolyte_assign_to_slot, name="acolyte_assign_to_slot"),
    path("people/acolyte/<int:acolyte_id>/slots/", views.acolyte_open_slots, name="acolyte_open_slots"),
    path("people/acolyte/<int:acolyte_id>/assign-multiple-slots/", views.acolyte_assign_to_multiple_slots, name="acolyte_assign_to_multiple_slots"),
    path("people/acolyte/<int:acolyte_id>/assign-multiple-slots/submit/", views.acolyte_assign_to_multiple_slots_submit, name="acolyte_assign_to_multiple_slots_submit"),
    path("people/acolyte/<int:acolyte_id>/assignments/<int:assignment_id>/remove/", views.acolyte_remove_assignment, name="acolyte_remove_assignment"),
    path("people/acolyte/<int:acolyte_id>/assignments/<int:assignment_id>/confirm/", views.acolyte_confirm_assignment, name="acolyte_confirm_assignment"),
    path("assignments/", views.my_assignments, name="my_assignments"),
    path("preferences/", views.my_preferences, name="my_preferences"),
    path("calendar/my.ics", views.calendar_feed, name="calendar_feed"),
    path("calendar/feed/token/", views.calendar_feed_token, name="calendar_feed_token"),
    path("preferences/availability/<int:rule_id>/delete/", views.delete_availability, name="delete_availability"),
    path("preferences/preferences/<int:pref_id>/delete/", views.delete_preference, name="delete_preference"),
    path("swap-requests/", views.swap_requests, name="swap_requests"),
    path("swap-requests/new/<int:assignment_id>/", views.swap_request_create, name="swap_request_create"),
    path("swap-requests/<int:swap_id>/assign/", views.swap_request_assign, name="swap_request_assign"),
    path("swap-requests/<int:swap_id>/accept/", views.swap_request_accept, name="swap_request_accept"),
    path("swap-requests/<int:swap_id>/reject/", views.swap_request_reject, name="swap_request_reject"),
    path("swap-requests/<int:swap_id>/approve/", views.swap_request_approve, name="swap_request_approve"),
    path("swap-requests/<int:swap_id>/cancel/", views.swap_request_cancel, name="swap_request_cancel"),
    path("claims/<int:claim_id>/choose/", views.position_claim_choose, name="position_claim_choose"),
    path("claims/<int:claim_id>/reject/", views.position_claim_reject, name="position_claim_reject"),
    path("claims/<int:claim_id>/cancel/", views.position_claim_cancel, name="position_claim_cancel"),
    path("claims/<int:claim_id>/approve/", views.position_claim_approve, name="position_claim_approve"),
    path("events/interest/", views.event_interest, name="event_interest"),
    path("settings/", views.parish_settings, name="parish_settings"),
    path("assignments/<int:assignment_id>/confirm/", views.confirm_assignment, name="confirm_assignment"),
    path("assignments/<int:assignment_id>/decline/", views.decline_assignment, name="decline_assignment"),
    path("assignments/<int:assignment_id>/cancel/", views.cancel_assignment, name="cancel_assignment"),
    path("parish/switch/<int:parish_id>/", views.switch_parish, name="switch_parish"),
] + account_urls

